### ISSUE TITLE
Apply to web view?

### ISSUE THREAD

**Issue by philchia** [delebedev/DLIDEKeyboard#1]
May i apply this to uiwebview's keyboard?

**Comment by delebedev** [comment]
I am sure that's possible, I will make some refactorings a bit later and notify you

**Comment by delebedev** [comment]
It's seems that UIWebView is the tricky one:
http://stackoverflow.com/questions/2105858/uiwebview-keyboard-getting-rid-of-the-previous-next-done-bar
http://ios-blog.co.uk/tutorials/rich-text-editing-a-simple-start-part-1/

All of existing solutions rely on private frameworks - not the best idea. 
So, I will close that
